name: dado
version: 0.5.1
author: Dart Authors <misc@dartlang.org>
description: An experimental dependency injection container for Dart
homepage: http://dart-lang.github.io/dado/
documentation: http://dart-lang.github.io/dado/docs/dado.html
dependencies:
  analyzer_experimental: any
  args: any
  logging: any
  path: any
  quiver: any

dev_dependencies:
  unittest: any
